// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn0Z_vVYNDOS6wOZdKz5y5OQ7RIIr-TfY',
    appId: '1:761112745058:web:cecd5eb18a358546fbad3b',
    messagingSenderId: '761112745058',
    projectId: 'avex-69c58',
    authDomain: 'avex-69c58.firebaseapp.com',
    storageBucket: 'avex-69c58.firebasestorage.app',
    measurementId: 'G-98Y14FEDDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATmo0LhFpXYcR_yy8s1YG0iGiZrrmXAYY',
    appId: '1:761112745058:android:3516205c1548199dfbad3b',
    messagingSenderId: '761112745058',
    projectId: 'avex-69c58',
    storageBucket: 'avex-69c58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi7dybCIQs6xMeS2XTz6J58Pjig2jmbcM',
    appId: '1:761112745058:ios:5a31cd5c5f03fd22fbad3b',
    messagingSenderId: '761112745058',
    projectId: 'avex-69c58',
    storageBucket: 'avex-69c58.firebasestorage.app',
    iosBundleId: 'com.example.avex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi7dybCIQs6xMeS2XTz6J58Pjig2jmbcM',
    appId: '1:761112745058:ios:5a31cd5c5f03fd22fbad3b',
    messagingSenderId: '761112745058',
    projectId: 'avex-69c58',
    storageBucket: 'avex-69c58.firebasestorage.app',
    iosBundleId: 'com.example.avex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn0Z_vVYNDOS6wOZdKz5y5OQ7RIIr-TfY',
    appId: '1:761112745058:web:7340478dbc11f407fbad3b',
    messagingSenderId: '761112745058',
    projectId: 'avex-69c58',
    authDomain: 'avex-69c58.firebaseapp.com',
    storageBucket: 'avex-69c58.firebasestorage.app',
    measurementId: 'G-3125LGCER6',
  );
}
